//Maya Preference 2020 (Release 1)
//
//

nameCommand
	-annotation "Tak_Display_MarkingMenu_PressNameCommand"
	-sourceType "mel"
	-command ("Tak_Display_MarkingMenu_Press")
	Tak_Display_MarkingMenu_PressNameCommand;

nameCommand
	-annotation "Tak_Display_MarkingMenu_ReleaseNameCommand"
	-sourceType "mel"
	-command ("Tak_Display_MarkingMenu_Release")
	Tak_Display_MarkingMenu_ReleaseNameCommand;

nameCommand
	-annotation "Tak_Selection_MarkingMenu_PressNameCommand"
	-sourceType "mel"
	-command ("Tak_Selection_MarkingMenu_Press")
	Tak_Selection_MarkingMenu_PressNameCommand;

nameCommand
	-annotation "Tak_Selection_MarkingMenu_ReleaseNameCommand"
	-sourceType "mel"
	-command ("Tak_Selection_MarkingMenu_Release")
	Tak_Selection_MarkingMenu_ReleaseNameCommand;

nameCommand
	-annotation "Tak_Rigging_MarkingMenu_PressNameCommand"
	-sourceType "mel"
	-command ("Tak_Rigging_MarkingMenu_Press")
	Tak_Rigging_MarkingMenu_PressNameCommand;

nameCommand
	-annotation "Tak_Rigging_MarkingMenu_ReleaseNameCommand"
	-sourceType "mel"
	-command ("Tak_Rigging_MarkingMenu_Release")
	Tak_Rigging_MarkingMenu_ReleaseNameCommand;

nameCommand
	-annotation "Tak_Skin_MarkingMenu_PressNameCommand"
	-sourceType "mel"
	-command ("Tak_Skin_MarkingMenu_Press")
	Tak_Skin_MarkingMenu_PressNameCommand;

nameCommand
	-annotation "Tak_Skin_MarkingMenu_ReleaseNameCommand"
	-sourceType "mel"
	-command ("Tak_Skin_MarkingMenu_Release")
	Tak_Skin_MarkingMenu_ReleaseNameCommand;

