//Maya Preference 2024 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "C:/Users/stakl/Downloads/CGTarian-Ray-2015-09-08.ma"
 -sva "RecentFilesList" "D:/tools/maya/modules/ironRig/RnD/fan.mb"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Zombie/Z_M_Mu_DashStuner/SkeletalMesh/_WIP/Z_M_Mu_DashStuner_SKeletalMesh_05_smoothGroup.ma"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Heroes/BeakSW_Re/SkeletalMesh/BeakSW_Re_SkeletalMesh_001.ma"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Heroes/BeakSW_Re/SkeletalMesh/_WIP/BeakSW_Re_SkeletalMesh_001.ma"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Heroes/BeakSW_Re/SkeletalMesh/_WIP/BeakSW_Re_SkeletalMesh_007_maxInfs.ma"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Heroes/BeakSW_Re/SkeletalMesh/_WIP/BeakSW_Re_SkeletalMesh_015_addClipMesh.ma"
 -sva "RecentFilesList" "C:/Users/stakl/Downloads/Ch_Dummy_Rig_v00_09/Ch_Dummy_Rig_v00_09.ma"
 -sva "RecentFilesList" "D:/Projects/SourceAssets/Characters/Zombie/Z_F_Li_Screamer_02/SkeletalMesh/_WIP/Z_F_Li_Screamer_02_SkelMesh_003_skin.ma"
 -sva "RecentFilesList" "C:/Users/stakl/Downloads/speedManagerTest.ma"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sva "RecentFilesTypeList" "mayaAscii"
 -sa "RecentProjectsList"
 -sva "RecentProjectsList" "D:/Projects/GoodbyeKansas_Rig/nicklas"
 -sva "RecentProjectsList" "D:/Quixel/Downloaded/DHI/9lrtkIMw_asset/8k/asset_source/MetaHumans"
 -sva "RecentProjectsList" "D:/Projects/Outsource_Facial_Rigs/Snappers_Rigs/Krafton_Facial_Rig"
 -sva "RecentProjectsList" "D:/Quixel/Downloaded/DHI/h5k9pbwV_asset/8k/asset_ue_source/MetaHumans"
 -sva "RecentProjectsList" "D:/Quixel/Downloaded/DHI/5q3urwQQ_asset/2k/asset_source/MetaHumans"
 -sva "RecentProjectsList" "D:/Quixel/Downloaded/DHI/6f0arCDN_asset/1k/asset_source/MetaHumans"
 -sva "RecentProjectsList" "D:/Projects/MadKeigun/maya/Asset/Ch/Keigun/groom/v001"
 -sva "RecentProjectsList" "D:/Projects/MadKeigun/maya/Asset/Ch/Keigun/groom"
 -sva "RecentProjectsList" "R:/Test/NirmMotion"
 -sva "RecentProjectsList" "D:/Megascans Library/Downloaded/DHI/l1s9UiYj_asset/1k/asset_source/MetaHumans"
 ;

